export const ErrorCodes = {
    IMAGE_REQUIRED: "IMAGE_REQUIRED",
    INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
    IMAGE_TOO_LARGE: "IMAGE_TOO_LARGE",
    AI_FAILED: "AI_RESPONSE_FAILED",
    INVALID_PROMPT: "INVALID_PROMPT"
};